// Auto-generated by scripts. Maps URL path -> legal page component.
import { MerchantServiceAgreement } from './MerchantServiceAgreement.jsx';
import { AdditionalMarketingTerms } from './AdditionalMarketingTerms.jsx';
import { ThirdPartyIntegrationTerms } from './ThirdPartyIntegrationTerms.jsx';
import { MoneyBackGuaranteeTerms } from './MoneyBackGuaranteeTerms.jsx';
import { PricePromiseMerchantTerms } from './PricePromiseMerchantTerms.jsx';
import { Privacy } from './Privacy.jsx';

export const LEGAL_PAGES = [
  { slug: 'merchantserviceagreement', title: "Merchant Service Agreement", Component: MerchantServiceAgreement },
  { slug: 'additionalmarketingterms', title: "Additional Marketing Terms", Component: AdditionalMarketingTerms },
  { slug: 'thirdpartyintegrationterms', title: "Third Party Integration Terms", Component: ThirdPartyIntegrationTerms },
  { slug: 'moneybackguaranteeterms', title: "Money Back Guarantee Terms", Component: MoneyBackGuaranteeTerms },
  { slug: 'pricepromisemerchantterms', title: "Price Promise Merchant Terms", Component: PricePromiseMerchantTerms },
  { slug: 'privacy', title: "Privacy Policy", Component: Privacy },
];

export const LEGAL_ROUTES = new Set(LEGAL_PAGES.map((p) => '/' + p.slug));
